name: Compile JSON Resume and Push to GH Pages

on:
  push:
    branches: ['main']
    paths: ['resume.json']
  workflow_dispatch:

jobs:
  compile-json-resume:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v3
    - name: Setting Git User
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name actions

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.17'

    - name: Build Resume PDF
      run: |
        npm ci
        npm run start-pdf

    - name: Push to pages branch
      run: |
          git add --force \*.pdf \*.html
          git commit -m "$(git log -1 --pretty='%s')"
          git push $(git ls-remote --get-url origin) main:prod --force
