name: Compile LaTeX Resume and Push To GH Pages

on:
  push:
    branches: ['main']
    paths: ['*.tex']
  workflow_dispatch:

jobs:
  compile_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v3
    - name: Setting Git User
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name actions-
    - name: Compile Main TeX File
      uses: xu-cheng/latex-action@v3
      with:
        root_file: ${{ env.RESUME_FILE_NAME }}.tex
        post_compile: "latexmk -c"
    - name: Push to pages branch
      run: |
          git add --force \*.tex \*.pdf
          git commit -m "$(git log -1 --pretty='%s')"
          git push $(git ls-remote --get-url origin) main:prod --force
